version: '2'
services:
  app:
     build:
       context: .
     container_name: m3app
     ports:
      - 8583:8583
     depends_on:
      - ddb
     environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ddb:5432/capgemini
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  ddb:
    image: 'postgres:13.1-alpine'
    container_name: ddb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=capgemini
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password