apiVersion: v1
kind: Service
metadata:
  name: dharshan-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8583
      targetPort: 8583
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
     # nodePort: 30007